version: '3'

services:

  redis:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/redis:latest
    ports:
      - 16379:6379
    container_name: redis
    volumes:
      - ./components/redis/data:/data
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      xiaomi-mall:
    command: redis-server --requirepass 1234 --appendonly yes

  mysql:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/mysql:8.0
    ports:
      - 13306:3306
    container_name: mysql
    volumes:
      - ./components/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    restart: always
    networks:
      xiaomi-mall:

networks:
  xiaomi-mall:
    driver: bridge
