version: '3'
services:
  redis:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/redis:latest
    container_name: redis
    ports:
      - 16379:6379
    volumes:
      - ./components/redis/data:/data
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      - xiaomi-mall
    command: redis-server --requirepass 1234 --appendonly yes

  mysql:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/mysql:8.0
    container_name: mysql
    ports:
      - 13306:3306
    volumes:
      - ./components/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Shanghai
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    networks:
      - xiaomi-mall

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./components/rabbitmq/data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      TZ: Asia/Shanghai
    restart: always
    networks:
      - xiaomi-mall

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - TZ=Asia/Shanghai   # <--- 这里改成了等号，修正了错误
    volumes:
      - ./components/es/data:/usr/share/elasticsearch/data
    restart: always
    networks:
      - xiaomi-mall

networks:
  xiaomi-mall:
    driver: bridge